/*
* SISTEMARE FILTER EXERCISES PAGE 
* SISTEMARE PAGINATORE EXERCISES PAGE
* MODULARE IL PAGINATORE E IL FILTER CON IL DATABASE OVVERO L'AGGIORNAMENTO DEI PARAMETRI DELLA GET IN BASE AI DATI FE
* TESTARE FORM EXERCISE - POST/PUT
* INSERIRE DELETE / UPDATE BTN DENTRO GLI EXERCISE DA ID > 1320
* INSERIRE NEL FORM ANCHE 2 DROPDOWN CON SECONDARY MUSCLES / EQUIPMENT






*/
