/*
* SISTEMARE FILTER EXERCISES PAGE 
* SISTEMARE PAGINATORE EXERCISES PAGE
* MODULARE IL PAGINATORE E IL FILTER CON IL DATABASE OVVERO L'AGGIORNAMENTO DEI PARAMETRI DELLA GET IN BASE AI DATI FE
* TESTARE FORM EXERCISE - POST/PUT
* INSERIRE DELETE / UPDATE BTN DENTRO GLI EXERCISE DA ID > 1320
* SISTEMARE BTN "NEW PROGRAM" + CREAZIONE PROGRAM-DETAILS
* CREAZIONE SERVIZI / COMPONENTI X ESEGUIRE STESSI LAVORI?




! VERIFICARE SIGNUP STESSA EMAIL -> ERRORE
! INSERIRE ERRORI DI LOGINMODEL
! INSERIRE ERRORI DI USERMODEL

*/
